title: "Benson Mugure â€” Software Engineering"
description: "Building secure, resilient, high-performing, cost-optimized cloud-native solutions."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Benson Mugure"
github_username: "Virgo-Alpha"
youtube_channel: "@dataslinger6379"
medium_username: "b.mugure"
exclude:
  - "README.md"
  - "node_modules"
  - "vendor"
  - ".bundle"
  - ".jekyll-cache"
