[build]
  command = "npm run build:kb && bundle exec jekyll build"
  publish = "_site"
  functions = "netlify/functions"

[context.production.environment]
  JEKYLL_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
